POST http://localhost:5000/members
Content-Type: application/json

{
    "name":"Oscar 2",
    "age":95
}

###
GET http://localhost:5000/members/5fc75b79f160a5698845e095


###

DELETE http://localhost:5000/members/5fc783b9967df0a584a92ff8